### ISSUE TITLE
Support OctoTree

### ISSUE THREAD

**Issue by martin-braun** [jerry1100/github-markdown-printer#18]
When you have OctoTree installed and pinned to the sidebar, the initial preview will have wrong margins: 

<img width="1032" alt="Screen Shot 2022-01-29 at 5 23 42 AM" src="https://user-images.githubusercontent.com/24259245/151647083-94466256-864b-480a-a567-1c94632628b5.png">

<img width="1005" alt="Screen Shot 2022-01-29 at 5 23 50 AM" src="https://user-images.githubusercontent.com/24259245/151647089-17e3e0d8-5e9c-440b-a5c6-e6287f9bd55c.png">

If I cancel and trigger this extension again it will be fixed, so no big deal, would still be nice if this could be addressed. Thanks so much.

**Comment by jerry1100** [comment]
Hey @martin-braun, thanks for the suggestion & sorry for the late reply.

I'm not keen on maintaining compatibility with third-party libraries, but I did take a look to see if it could be done with octotree in a generic way.

Unfortunately it doesn't seem like it because octotree is modifying the html node with octotree-specific styles, things I don't want to maintain in this extension.
<img width="539" alt="image" src="https://user-images.githubusercontent.com/18181641/163112833-2f205250-ea28-4e03-a61c-c75b35f63581.png">

I suggest, like you said, just unpinning the octotree sidebar when you want to print markdown. Or open a new incognito window (with octotree extension disabled and GMP enabled).
