### ISSUE TITLE
Page Breaks Not Working

### ISSUE THREAD

**Issue by deivid77** [jerry1100/github-markdown-printer#28]
Hello,

I'm experiencing an issue with page breaks when printing Markdown using your stunning Chrome extension. 
I'm using the 
`<div style="page-break-after: always;"></div> `
syntax for page breaks, but it seems the extension is not recognizing them during printing.

Maybe the code expects another sintax for page breaks.

Addressing this would make the documents even more beautiful. 
Thank you so much.

**Comment by jerry1100** [comment]
Hey Dave, thanks for reporting. Do you mind providing a screenshot to help me understand the issue better?

**Comment by deivid77** [comment]
Sure!
I hope it helps to clarify.

![image](https://github.com/jerry1100/github-markdown-printer/assets/6113575/b8938fff-8698-4558-ac29-0361156eca0c)
![image](https://github.com/jerry1100/github-markdown-printer/assets/6113575/d57d7c06-00e8-4aa6-aa77-34fba8d00f87)
![image](https://github.com/jerry1100/github-markdown-printer/assets/6113575/197535af-99ea-457b-a20f-97e6bce5d919)
![image](https://github.com/jerry1100/github-markdown-printer/assets/6113575/033e8906-050e-4479-a29c-68d440e4765e)

**Comment by jerry1100** [comment]
It seems like GitHub Flavored Markdown doesn't support page breaks - it's being stripped out in the HTML.

Here I'm rendering a page break:
<img width="715" alt="image" src="https://github.com/jerry1100/github-markdown-printer/assets/18181641/430c13a9-36ed-4737-96e1-f9770d9dcf58">

But when I inspect the HTML, it's not there:
<img width="570" alt="image" src="https://github.com/jerry1100/github-markdown-printer/assets/18181641/76abffde-6cd5-48b5-ac46-6436f48a97c3">

Copilot had this to say:

> GitHub applies a sanitization process to all Markdown files, which includes stripping out most HTML tags, including <div>, for security reasons. This is to prevent cross-site scripting (XSS) attacks. As a result, your page-break-before style is not being applied because the <div> tag is being removed.

So it seems like it's not possible, despite what some people online are saying. Maybe GitHub removed this functionality recently.

I'm going to close this since it doesn't seem like there's anything we can do, but feel free to reopen if you find something.
